version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: dietidealsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dietideals
    ports:
      - "5432:5432"
    restart: always
  spring-boot-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/dietidealsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: dietideals
