package com.example.dietideals_app.model.enum

enum class CategoriaAsta {
    ELETTRONICA, INFORMATICA, GIOCATTOLI, ALIMENTARI, SERVIZI,
    ARREDAMENTO, AUTO_E_MOTO, LIBRI, ABBIGLIAMENTO, ATTREZZI_E_UTENSILI, BELLEZZA, MUSICA_E_ARTE
}