spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ingswProva
    username: postgres
    password: 26102002
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
